[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "azure-ai-evaluation==1.15.3",
    "azure-ai-inference==1.0.0b9",
    "azure-ai-projects==2.0.0b4",
    "azure-ai-agents==1.2.0b6",
    "azure-cosmos==4.15.0",
    "azure-identity==1.25.2",
    "azure-monitor-events-extension==0.1.0",
    "azure-monitor-opentelemetry==1.8.6",
    "azure-search-documents==11.6.0",
    "fastapi==0.135.0",
    "openai==2.24.0",
    "opentelemetry-api==1.39.1",
    "opentelemetry-exporter-otlp-proto-grpc==1.39.1",
    "opentelemetry-exporter-otlp-proto-http==1.39.1",
    "opentelemetry-instrumentation-fastapi==0.60b1",
    "opentelemetry-instrumentation-openai==0.52.6",
    "opentelemetry-sdk==1.39.1",
    "pytest==9.0.2",
    "pytest-asyncio==1.3.0",
    "pytest-cov==7.0.0",
    "python-dotenv==1.2.1",
    "python-multipart==0.0.22",
    "semantic-kernel==1.39.4",
    "uvicorn==0.41.0",
    "pylint-pydantic==0.4.1",
    "pexpect==4.9.0",
    "mcp==1.26.0",
    "werkzeug==3.1.6",
    "azure-core==1.38.2",
    "agent-framework>=1.0.0b251105",
]
