name: Test Workflow with Coverage

on:
  push:
    branches:
      - main
      - demo-v4
      - dev-v4
      - macae-v4-unittestcases-kd
    paths:
      - 'src/backend/**/*.py'
      - 'src/tests/**/*.py'
      - 'src/mcp_server/**/*.py'
      - 'src/**/pyproject.toml'
      - 'pytest.ini'
      - 'conftest.py'
      - 'src/backend/requirements.txt'
      - '.github/workflows/test.yml'
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize
    branches:
      - main
      - demo-v4
      - dev-v4
    paths:
      - 'src/backend/**/*.py'
      - 'src/tests/**/*.py'
      - 'src/mcp_server/**/*.py'
      - 'pytest.ini'
      - 'conftest.py'
      - 'src/backend/requirements.txt'
      - 'src/**/pyproject.toml'
      - '.github/workflows/test.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/backend/requirements.txt

      - name: Check if test files exist
        id: check_tests
        run: |
          if [ -z "$(find src -type f -name 'test_*.py')" ]; then
            echo "No test files found, skipping tests."
            echo "skip_tests=true" >> $GITHUB_ENV
          else
            echo "Test files found, running tests."
            echo "skip_tests=false" >> $GITHUB_ENV
          fi

      - name: Run tests with coverage
        if: env.skip_tests == 'false'
        run: |
          python -m pytest src/tests/backend/test_app.py --cov=backend --cov-config=.coveragerc
          python -m pytest src/tests/backend --cov=backend --cov-append --cov-report=term --cov-config=.coveragerc --ignore=src/tests/backend/test_app.py

      # - name: Run tests with coverage
      #   if: env.skip_tests == 'false'
      #   run: |
      #     pytest --cov=. --cov-report=term-missing --cov-report=xml --ignore=tests/e2e-test/tests
          
      - name: Skip coverage report if no tests
        if: env.skip_tests == 'true'
        run: |
          echo "Skipping coverage report because no tests were found."
